package dev.tossfront.record;

import android.animation.ValueAnimator;
import android.content.*;
import android.content.res.ColorStateList;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.session.PlaybackState;
import android.media.AudioManager;
import android.os.*;
import android.text.TextUtils;
import android.view.*;
import android.view.animation.PathInterpolator;
import android.widget.*;

public final class RecordPanel extends FrameLayout implements SessionRepository.Observer {
    public interface Host { void openSource(); void openAudio(); void showRecord(); void connectionSettings(); void audioPermission(); void cameraPermission(); void appearanceChanged(); void close(); }
    private static final PathInterpolator EASE=new PathInterpolator(.22f,1,.36f,1);
    private final SessionRepository repository;
    private final Handler main=new Handler(Looper.getMainLooper());
    private final Appearance appearance;
    private final VisualStage stage;
    private final ScrollView content;private final View visualSpace,scrim;
    private final TextView status,title,artist,elapsed,total,hint,connection;
    private final Control previous,toggle,next,loop,history;
    private final SeekBar seek,volume;
    private final AudioManager audioManager;
    private final HandDisplay handDisplay=new HandDisplay();private final CameraGesture camera;private final HandOverlay handOverlay;private final TextView cameraLabel;private boolean cameraAllowed=true;private long gestureFeedbackUntil;
    private final LinearLayout volumeRow;
    private final TextView volumeText,timerText;
    private final Control timerButton,speaker;
    private TimerSheet timerSheet;
    private boolean volumeDragging;
    private final LinearLayout body;
    private final LinearLayout heading,time,controls;
    private final Host host;
    private final boolean overlay,separateScene;
    private TextView floating;
    private boolean attached,dragging,closing,entered;
    private int ticks;
    private int sheets;
    private AppearanceSheet settingsSheet;
    private HistorySheet historySheet;
    private boolean headerHidden,waking;
    private final Runnable hideHeader=new Runnable(){public void run(){if(!attached||sheets>0||getWindowVisibility()!=VISIBLE)return;if(volumeDragging){main.postDelayed(this,1000);return;}headerHidden=true;volumeRow.setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO_HIDE_DESCENDANTS);heading.setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO_HIDE_DESCENDANTS);if(appearance.motion()){heading.animate().alpha(0).setDuration(220).start();volumeRow.animate().alpha(0).setDuration(220).start();}else{heading.setAlpha(0);volumeRow.setAlpha(0);}}};
    private ValueAnimator palette;
    private final BroadcastReceiver screenState=new BroadcastReceiver(){public void onReceive(Context context,Intent intent){refreshCamera();}};
    private final int[] colors=new int[6];
    private final Runnable clock=new Runnable(){public void run(){if(!attached||getWindowVisibility()!=VISIBLE)return;stage.refresh();updateTime();updateStatus();updateTimer();if(++ticks%10==0)updateVolume();if(ticks%20==0)repository.connect();main.postDelayed(this,100);}};

    public RecordPanel(Context context,Host host,boolean overlay) {this(context,host,overlay,null);}
    RecordPanel(Context context,Host host,boolean overlay,FrameLayout externalScene) {
        super(context);this.host=host;this.overlay=overlay;this.cameraAllowed=overlay;this.separateScene=externalScene!=null;appearance=new Appearance(context);repository=SessionRepository.get(context);setClipToPadding(false);audioManager=(AudioManager)context.getSystemService(Context.AUDIO_SERVICE);
        if(overlay)setOnApplyWindowInsetsListener((view,insets)->{if(appearance.immersive)view.setPadding(0,0,0,0);else view.setPadding(0,insets.getSystemWindowInsetTop(),0,insets.getSystemWindowInsetBottom());return insets;});
        stage=new VisualStage(context,externalScene);addView(stage,new FrameLayout.LayoutParams(-1,-1));scrim=new View(context);scrim.setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO);addView(scrim,new FrameLayout.LayoutParams(-1,-1));content=new ScrollView(context);content.setFillViewport(true);content.setVerticalScrollBarEnabled(false);content.setClipToPadding(false);addView(content,new FrameLayout.LayoutParams(-1,-1));body=new LinearLayout(context);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(24),dp(8),dp(24),dp(16));content.addView(body);
        heading=new LinearLayout(context);heading.setGravity(Gravity.CENTER_VERTICAL);
        timerText=label("",11);timerText.setGravity(Gravity.CENTER_VERTICAL);heading.addView(timerText,new LinearLayout.LayoutParams(0,dp(48),1));history=new Control(context,4,appearance);history.setContentDescription("재생 기록 · 즐겨찾기");history.setOnClickListener(v->showHistory());heading.addView(history,new LinearLayout.LayoutParams(dp(48),dp(48)));
        timerButton=new Control(context,8,appearance);timerButton.setContentDescription("재생 정지 예약");timerButton.setOnClickListener(v->showTimer());heading.addView(timerButton,new LinearLayout.LayoutParams(dp(48),dp(48)));
        TextView options=textButton("•••",this::showSettings);options.setTextSize(18);options.setContentDescription("화면 설정");heading.addView(options,new LinearLayout.LayoutParams(dp(48),dp(48)));
        TextView close=textButton(overlay?"×":"홈",host::close);close.setContentDescription(overlay?"레코드 화면 닫기":"홈으로");close.setTextSize(overlay?24:13);heading.addView(close,new LinearLayout.LayoutParams(dp(48),dp(48)));body.addView(heading);
        if(!overlay){floating=textButton("재생 화면 열기",host::showRecord);add(body,floating,4);}
        visualSpace=new View(context);int screen=(int)(getResources().getDisplayMetrics().heightPixels/getResources().getDisplayMetrics().density);int height=Math.min(295,Math.max(210,screen-(overlay?390:438)));
        LinearLayout.LayoutParams stageParams=new LinearLayout.LayoutParams(-1,dp(height));stageParams.topMargin=dp(4);body.addView(visualSpace,stageParams);visualSpace.setOnLongClickListener(v->{showSettings();return true;});visualSpace.addOnLayoutChangeListener((v,l,t,r,b,ol,ot,or,ob)->placeStage());content.setOnScrollChangeListener((v,x,y,oldX,oldY)->placeStage());
        // Controls and hand paths use GPU display lists; WebGL retains its separate window.
        LinearLayout details=new LinearLayout(context);details.setOrientation(LinearLayout.VERTICAL);body.addView(details);
        status=label("",12);status.setGravity(Gravity.CENTER);status.setMinHeight(dp(18));add(details,status,0);
        title=label("재생 중인 곡이 없어요",22);title.setTypeface(Typeface.create("sans-serif-medium",0));title.setMinLines(2);title.setMaxLines(2);title.setEllipsize(TextUtils.TruncateAt.END);add(details,title,12);
        artist=label("YouTube 웹에서 영상을 재생해 주세요.",14);artist.setSingleLine(true);artist.setEllipsize(TextUtils.TruncateAt.END);add(details,artist,4);
        seek=new SeekBar(context);seek.setMax(10000);seek.setContentDescription("재생 위치");LinearLayout.LayoutParams seekParams=new LinearLayout.LayoutParams(-1,dp(48));seekParams.topMargin=dp(6);details.addView(seek,seekParams);
        time=new LinearLayout(context);elapsed=label("0:00",13);total=label("—",13);elapsed.setFontFeatureSettings("tnum");total.setFontFeatureSettings("tnum");total.setGravity(Gravity.END);time.addView(elapsed,new LinearLayout.LayoutParams(0,-2,1));time.addView(total,new LinearLayout.LayoutParams(0,-2,1));details.addView(time);
        seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar bar){dragging=true;seek.getParent().requestDisallowInterceptTouchEvent(true);}public void onProgressChanged(SeekBar bar,int value,boolean user){if(user&&repository.duration()>0)elapsed.setText(format(repository.duration()*value/bar.getMax()));}public void onStopTrackingTouch(SeekBar bar){repository.seek(repository.duration()*bar.getProgress()/bar.getMax());dragging=false;seek.getParent().requestDisallowInterceptTouchEvent(false);}});
        controls=new LinearLayout(context);controls.setGravity(Gravity.CENTER);previous=new Control(context,0,appearance);toggle=new Control(context,1,appearance);next=new Control(context,3,appearance);loop=new Control(context,5,appearance);
        previous.setOnClickListener(v->repository.previous());toggle.setOnClickListener(v->repository.toggle());next.setOnClickListener(v->repository.next());loop.setOnClickListener(v->repository.cycleLoop());controls.addView(previous,new LinearLayout.LayoutParams(dp(48),dp(64)));LinearLayout.LayoutParams center=new LinearLayout.LayoutParams(dp(72),dp(72));center.setMargins(dp(12),0,dp(12),0);controls.addView(toggle,center);controls.addView(next,new LinearLayout.LayoutParams(dp(48),dp(64)));controls.addView(loop,new LinearLayout.LayoutParams(dp(48),dp(64)));add(details,controls,14);
        volumeRow=new LinearLayout(context);volumeRow.setGravity(Gravity.CENTER_VERTICAL);speaker=new Control(context,9,appearance);speaker.setClickable(false);speaker.setContentDescription("기기 미디어 볼륨");volumeRow.addView(speaker,new LinearLayout.LayoutParams(dp(32),dp(44)));volume=new SeekBar(context);volume.setMax(Math.max(1,audioManager.getStreamMaxVolume(AudioManager.STREAM_MUSIC)));volume.setContentDescription("기기 미디어 볼륨");volumeRow.addView(volume,new LinearLayout.LayoutParams(0,dp(44),1));volumeText=label("",11);volumeText.setGravity(Gravity.CENTER);volumeRow.addView(volumeText,new LinearLayout.LayoutParams(dp(40),dp(44)));volume.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar b){volumeDragging=true;}public void onProgressChanged(SeekBar b,int value,boolean user){if(user){try{audioManager.setStreamVolume(AudioManager.STREAM_MUSIC,value,0);}catch(SecurityException ignored){}volumeText.setText(Math.round(value*100f/b.getMax())+"%");}}public void onStopTrackingTouch(SeekBar b){volumeDragging=false;updateVolume();revealHeader();}});add(details,volumeRow,4);updateVolume();
        hint=label("",12);hint.setGravity(Gravity.CENTER);add(details,hint,10);
        connection=textButton("재생 정보 연결 설정",host::connectionSettings);add(details,connection,8);
        handOverlay=new HandOverlay(context);addView(handOverlay,new FrameLayout.LayoutParams(-1,-1));cameraLabel=label("",11);cameraLabel.setPadding(dp(8),dp(5),dp(8),dp(5));FrameLayout.LayoutParams cameraTag=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.START);cameraTag.leftMargin=dp(24);cameraTag.topMargin=dp(66);addView(cameraLabel,cameraTag);cameraLabel.setVisibility(GONE);
        camera=new CameraGesture(context,new CameraGesture.Listener(){public void status(String value){if(cameraLabel!=null){cameraLabel.setText(value);if(!camera.running()){handDisplay.clear();stage.audio.gesture.clear();handOverlay.clear();}}}public void frame(java.util.List<HandGestureCore.Hand> hands,HandGestureCore.Output output){if(!attached||closing)return;if(appearance.handVisual){handDisplay.update(hands,SystemClock.elapsedRealtime());HandGestureCore.Output visual=new HandGestureCore.Output();handDisplay.output(visual);stage.audio.gesture.update(visual);}else{handDisplay.clear();stage.audio.gesture.clear();}handOverlay.update(hands,appearance.accent(),appearance.handTrace,appearance.handTrail);stage.gestureChanged();if(SystemClock.elapsedRealtime()>=gestureFeedbackUntil&&!TextUtils.equals(cameraLabel.getText(),camera.status()))cameraLabel.setText(camera.status());if(sheets==0&&cameraAllowed&&getWindowVisibility()==VISIBLE){if(output.volumeDelta!=0&&appearance.handVolume){if(!audioManager.isVolumeFixed()){int max=audioManager.getStreamMaxVolume(AudioManager.STREAM_MUSIC),current=audioManager.getStreamVolume(AudioManager.STREAM_MUSIC),target=Math.max(0,Math.min(max,current+output.volumeDelta));audioManager.setStreamVolume(AudioManager.STREAM_MUSIC,target,0);int playback=GestureVolume.playback(output.volumeDelta,current,target);if(repository.connected()){if(playback<0){repository.pause();android.util.Log.i("FrontRecordHands","gesture_volume_pause");}else if(playback>0&&!repository.playing()){repository.play();android.util.Log.i("FrontRecordHands","gesture_volume_resume");}}updateVolume();gestureFeedback(target==0&&playback<0?"볼륨 0% · 일시정지":"볼륨 "+Math.round(target*100f/max)+"%");android.util.Log.i("FrontRecordHands","gesture_volume");}}if(output.playback!=0&&appearance.handClap&&repository.connected()){if(output.playback>0)repository.play();else repository.pause();gestureFeedback(output.playback>0?"재생":"일시정지");android.util.Log.i("FrontRecordHands",output.playback>0?"gesture_play":"gesture_pause");}if(output.navigation!=0&&appearance.handNext){boolean forward=output.navigation>0;if(repository.canSkip(output.navigation)){if(forward)repository.next();else repository.previous();gestureFeedback(forward?"다음 곡":"이전 곡");android.util.Log.i("FrontRecordHands",forward?"gesture_next":"gesture_previous");}else{gestureFeedback(forward?"다음 곡 없음":"이전 곡 없음");android.util.Log.i("FrontRecordHands","gesture_navigation_unavailable");}}}}});
        renderer();setPalette(new int[]{appearance.bg(),appearance.surface(),appearance.text(),appearance.muted(),appearance.track(),appearance.accent()});stage.applyAppearance(appearance);
    }
    private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
    private TextView label(String text,int size){TextView v=new TextView(getContext());v.setText(text);v.setTextSize(size);v.setTextColor(appearance.text());v.setLayerType(View.LAYER_TYPE_NONE,null);return v;}
    private GradientDrawable shape(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(12));return d;}
    private void add(LinearLayout parent,View view,int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(top);parent.addView(view,p);}
    private TextView textButton(String text,Runnable action){TextView v=label(text,13);v.setGravity(Gravity.CENTER);v.setMinHeight(dp(48));v.setPadding(dp(8),dp(8),dp(8),dp(8));v.setClickable(true);v.setFocusable(true);v.setOnClickListener(x->action.run());press(v,appearance);return v;}
    static void press(View view,Appearance a){view.setOnTouchListener((v,event)->{if(!v.isEnabled())return false;int action=event.getAction();if(action==MotionEvent.ACTION_DOWN||action==MotionEvent.ACTION_UP||action==MotionEvent.ACTION_CANCEL){float scale=action==MotionEvent.ACTION_DOWN?.97f:1;if(a.motion())v.animate().scaleX(scale).scaleY(scale).setDuration(110).setInterpolator(EASE).start();else{v.setScaleX(scale);v.setScaleY(scale);}}return false;});}
    private void revealHeader(){headerHidden=false;heading.animate().cancel();heading.setAlpha(1);volumeRow.animate().cancel();volumeRow.setAlpha(1);volumeRow.setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_AUTO);heading.setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_AUTO);main.removeCallbacks(hideHeader);if(attached&&sheets==0)main.postDelayed(hideHeader,5000);}
    @Override public boolean dispatchTouchEvent(MotionEvent event){if(event.getAction()==MotionEvent.ACTION_DOWN){waking=headerHidden;revealHeader();}if(waking){if(event.getAction()==MotionEvent.ACTION_UP||event.getAction()==MotionEvent.ACTION_CANCEL)waking=false;return true;}return super.dispatchTouchEvent(event);}
    private void sheetClosed(){sheets=Math.max(0,sheets-1);refreshCamera();revealHeader();}
    private void dismissSheets(){if(settingsSheet!=null){settingsSheet.dismiss();settingsSheet=null;}if(historySheet!=null){historySheet.dismiss();historySheet=null;}if(timerSheet!=null){timerSheet.dismiss();timerSheet=null;}}
    private void showSettings(){dismissSheets();sheets++;refreshCamera();revealHeader();settingsSheet=new AppearanceSheet(getContext(),appearance,host,this::applyAppearance,()->{stage.audio.retry();changed();},this::sheetClosed,overlay,camera);settingsSheet.show();}
    private void showHistory(){dismissSheets();sheets++;refreshCamera();revealHeader();historySheet=new HistorySheet(getContext(),appearance,overlay,()->{if(!overlay)host.showRecord();},this::sheetClosed);historySheet.show();}
    private void showTimer(){dismissSheets();sheets++;refreshCamera();revealHeader();timerSheet=new TimerSheet(getContext(),appearance,overlay,this::updateTimer,this::sheetClosed);timerSheet.show();}
    private void updateTimer(){PlaybackTimer t=PlaybackTimer.get(getContext());updateLabel(timerText,t.plan.kind==TimerPlan.NONE?"":t.plan.kind==TimerPlan.TRACK_END?"곡 종료 후":SessionRepository.formatTimer(t.plan.remaining(System.currentTimeMillis())),false);timerText.setContentDescription(t.label());timerButton.setActivated(t.plan.kind!=TimerPlan.NONE);}
    private void gestureFeedback(String text){gestureFeedbackUntil=SystemClock.elapsedRealtime()+2200;cameraLabel.setText(text);}
    public void cameraVisible(boolean visible){cameraAllowed=visible;refreshCamera();}
    private void refreshCamera(){if(camera==null)return;boolean enabled=attached&&!closing&&cameraAllowed&&getWindowVisibility()==VISIBLE&&((PowerManager)getContext().getSystemService(Context.POWER_SERVICE)).isInteractive()&&appearance.handCamera;camera.commands(sheets==0);camera.configure(enabled,appearance.handCameraIndex,appearance.handFast);cameraLabel.setVisibility(appearance.handCamera?VISIBLE:GONE);cameraLabel.setTextColor(appearance.text());cameraLabel.setBackground(shape(appearance.surface()));if(!enabled){handDisplay.clear();stage.audio.gesture.clear();handOverlay.clear();stage.gestureChanged();}}
    private void updateVolume(){if(volumeDragging)return;int value=audioManager.getStreamVolume(AudioManager.STREAM_MUSIC);volume.setProgress(value);volumeText.setText(Math.round(value*100f/volume.getMax())+"%");volume.setEnabled(!audioManager.isVolumeFixed());}
    private void renderer(){setLayerType(View.LAYER_TYPE_NONE,null);}
    public void preferencesChanged(){appearance.reload();applyAppearance();}
    private void applyAppearance(){refreshCamera();renderer();stage.applyAppearance(appearance);host.appearanceChanged();requestApplyInsets();int[] target={appearance.bg(),appearance.surface(),appearance.text(),appearance.muted(),appearance.track(),appearance.accent()};if(palette!=null)palette.cancel();if(appearance.motion()&&!java.util.Arrays.equals(colors,target)){int[] from=colors.clone();palette=ValueAnimator.ofFloat(0,1);palette.setDuration(200);palette.setInterpolator(EASE);palette.addUpdateListener(v->{float f=(float)v.getAnimatedValue();int[] mixed=new int[6];for(int i=0;i<6;i++)mixed[i]=blend(from[i],target[i],f);setPalette(mixed);});palette.start();}else setPalette(target);changed();}
    private int blend(int a,int b,float t){return Color.rgb(Math.round(Color.red(a)+(Color.red(b)-Color.red(a))*t),Math.round(Color.green(a)+(Color.green(b)-Color.green(a))*t),Math.round(Color.blue(a)+(Color.blue(b)-Color.blue(a))*t));}
    private void setPalette(int[] value){System.arraycopy(value,0,colors,0,6);setBackgroundColor(separateScene&&appearance.mode>=7?Color.TRANSPARENT:colors[0]);int base=colors[0]&0xffffff;scrim.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{base,base,0x64000000|base,0xeb000000|base,0xff000000|base}));for(TextView v:new TextView[]{title,artist,elapsed,total,status,hint,connection})if(v!=null)v.setTextColor(v==title?colors[2]:colors[3]);seek.setProgressTintList(ColorStateList.valueOf(colors[5]));volume.setProgressTintList(ColorStateList.valueOf(colors[5]));volume.setThumbTintList(ColorStateList.valueOf(colors[5]));volume.setProgressBackgroundTintList(ColorStateList.valueOf(colors[4]));volumeText.setTextColor(colors[3]);timerText.setTextColor(colors[3]);seek.setProgressBackgroundTintList(ColorStateList.valueOf(colors[4]));seek.setThumbTintList(ColorStateList.valueOf(colors[5]));for(Control control:new Control[]{previous,toggle,next,history,loop,timerButton,speaker})control.colors(colors[5],colors[0],colors[2]);for(TextView v:new TextView[]{title,artist,elapsed,total,status,hint,connection,volumeText,timerText})v.setTypeface(appearance.theme==4?Typeface.MONOSPACE:Typeface.create("sans-serif",0));if(floating!=null){floating.setTextColor(colors[2]);floating.setBackground(shape(colors[1]));}for(int i=0;i<heading.getChildCount();i++){View v=heading.getChildAt(i);if(v instanceof TextView)((TextView)v).setTextColor(colors[2]);}}
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();attached=true;IntentFilter screenFilter=new IntentFilter(Intent.ACTION_SCREEN_ON);screenFilter.addAction(Intent.ACTION_SCREEN_OFF);if(Build.VERSION.SDK_INT>=33)getContext().registerReceiver(screenState,screenFilter,Context.RECEIVER_NOT_EXPORTED);else getContext().registerReceiver(screenState,screenFilter);closing=false;setAlpha(1);setTranslationY(0);renderer();repository.observe(this);refreshCamera();main.post(clock);revealHeader();if(!entered&&appearance.motion()){entered=true;body.setAlpha(0);body.setTranslationY(dp(6));body.animate().alpha(1).translationY(0).setDuration(220).setInterpolator(EASE).start();}}
    @Override protected void onDetachedFromWindow(){attached=false;getContext().unregisterReceiver(screenState);camera.close();stage.audio.gesture.clear();dismissSheets();main.removeCallbacks(clock);main.removeCallbacks(hideHeader);heading.animate().cancel();volumeRow.animate().cancel();repository.remove(this);animate().cancel();body.animate().cancel();if(palette!=null)palette.cancel();super.onDetachedFromWindow();}
    @Override protected void onWindowVisibilityChanged(int visibility){super.onWindowVisibilityChanged(visibility);if(attached){main.removeCallbacks(clock);refreshCamera();if(visibility==VISIBLE)main.post(clock);}}
    public void dismiss(Runnable finish){if(closing)return;closing=true;camera.stop();if(appearance.motion())animate().alpha(0).translationY(dp(4)).setDuration(130).setInterpolator(EASE).withEndAction(finish).start();else finish.run();}
    private void updateLabel(TextView view,String value,boolean motion){if(TextUtils.equals(view.getText(),value))return;view.animate().cancel();view.setText(value);if(motion&&appearance.motion()){view.setAlpha(.6f);view.setTranslationY(dp(2));view.animate().alpha(1).translationY(0).setDuration(160).setInterpolator(EASE).start();}else{view.setAlpha(1);view.setTranslationY(0);}}
    @Override public void changed(){updateLabel(title,repository.title(),true);updateLabel(artist,repository.artist(),true);stage.update(repository.playing(),repository.artwork());toggle.setMode(repository.playing()?2:1);toggle.setContentDescription(repository.playing()?"일시정지":"재생");toggle.setEnabled(repository.supports(PlaybackState.ACTION_PLAY|PlaybackState.ACTION_PAUSE|PlaybackState.ACTION_PLAY_PAUSE));title.setVisibility(appearance.showTitle?VISIBLE:GONE);artist.setVisibility(appearance.showTitle?VISIBLE:GONE);seek.setVisibility(appearance.showProgress?VISIBLE:GONE);time.setVisibility(appearance.showProgress?VISIBLE:GONE);toggle.setVisibility(appearance.showPlay?VISIBLE:GONE);previous.setVisibility(appearance.showSkip?VISIBLE:GONE);next.setVisibility(appearance.showSkip?VISIBLE:GONE);boolean canPrevious=repository.canSkip(-1),canNext=repository.canSkip(1);previous.setEnabled(canPrevious);next.setEnabled(canNext);previous.setContentDescription(canPrevious?"이전 곡":"이전 곡 없음");next.setContentDescription(canNext?"다음 곡":"다음 곡 없음");loop.setVisibility(appearance.showLoop?VISIBLE:GONE);loop.setMode(5+repository.loopMode());loop.setContentDescription(repository.loopMode()==0?"반복 꺼짐":repository.loopMode()==1?"한 곡 반복":"즐겨찾기 목록 반복");controls.setVisibility(appearance.showPlay||appearance.showLoop||previous.getVisibility()==VISIBLE||next.getVisibility()==VISIBLE?VISIBLE:GONE);seek.setEnabled(repository.supports(PlaybackState.ACTION_SEEK_TO)&&repository.duration()>0&&!repository.advertisement());connection.setVisibility(repository.hasAccess()?GONE:VISIBLE);updateLabel(hint,!overlay?"웹에서 재생 후 ‘재생 화면 열기’를 눌러 주세요.":"",false);hint.setVisibility(overlay?GONE:VISIBLE);volumeRow.setVisibility(appearance.showVolume?VISIBLE:GONE);setKeepScreenOn(repository.playing());resizeStage();updateTime();updateStatus();}
    @Override protected void onSizeChanged(int w,int h,int ow,int oh){super.onSizeChanged(w,h,ow,oh);if(stage!=null)resizeStage();}
    private void resizeStage(){float density=getResources().getDisplayMetrics().density;int screen=Math.round((getHeight()>0?getHeight()-getPaddingTop()-getPaddingBottom():getResources().getDisplayMetrics().heightPixels)/density);int available=Math.max(120,screen-56-18-16-(overlay?0:76)-(appearance.showTitle?104:0)-(appearance.showProgress?78:0)-(appearance.showVolume?48:0)-(controls.getVisibility()==VISIBLE?90:0));int height=dp(Math.max(90,Math.round(available*appearance.area/100f)));ViewGroup.LayoutParams params=visualSpace.getLayoutParams();if(params.height!=height){params.height=height;visualSpace.setLayoutParams(params);}post(this::placeStage);}
    private void placeStage(){if(visualSpace.getHeight()>0){stage.setOpenArea(content.getTop()+body.getTop()+visualSpace.getTop()-content.getScrollY()-stage.getTop(),visualSpace.getHeight());}}
    private void updateStatus(){String value=!repository.seekStatus().isEmpty()?repository.seekStatus():repository.error()?"웹 화면에서 재생 오류를 확인해 주세요":repository.buffering()?"불러오는 중":stage.analysisStatus();updateLabel(status,value,false);}
    private void updateTime(){if(!dragging){long position=repository.position(),duration=repository.duration();updateLabel(elapsed,format(position),false);updateLabel(total,duration>0?format(duration):"—",false);int progress=duration>0?(int)(position*seek.getMax()/duration):0;seek.setProgress(progress,repository.playing()&&appearance.motion()&&Math.abs(progress-seek.getProgress())<200);}}
    static String format(long ms){long seconds=Math.max(0,ms/1000);return seconds>=3600?String.format(java.util.Locale.ROOT,"%d:%02d:%02d",seconds/3600,(seconds/60)%60,seconds%60):String.format(java.util.Locale.ROOT,"%d:%02d",seconds/60,seconds%60);}

    static final class Control extends View {
        int mode,oldMode,accent,paper,ink;private float mix=1;private ValueAnimator icon;private final Appearance a;private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);private final Path triangle=new Path();
        Control(Context c,int mode,Appearance a){super(c);this.mode=mode;this.a=a;setLayerType(View.LAYER_TYPE_NONE,null);setClickable(true);setFocusable(true);setContentDescription(mode==0?"이전 영상":mode==3?"다음 영상":"재생");press(this,a);}
        void colors(int accent,int paper,int ink){this.accent=accent;this.paper=paper;this.ink=ink;invalidate();}
        void setMode(int value){if(mode==value)return;if(icon!=null)icon.cancel();oldMode=mode;mode=value;if(!a.motion()){mix=1;invalidate();return;}mix=0;icon=ValueAnimator.ofFloat(0,1);icon.setDuration(160);icon.setInterpolator(EASE);icon.addUpdateListener(v->{mix=(float)v.getAnimatedValue();invalidate();});icon.start();}
        @Override public void setEnabled(boolean enabled){if(isEnabled()==enabled)return;super.setEnabled(enabled);if(a.motion())animate().alpha(enabled?1:.3f).setDuration(150).setInterpolator(EASE).start();else setAlpha(enabled?1:.3f);}
        @Override protected void onDetachedFromWindow(){if(icon!=null)icon.cancel();animate().cancel();super.onDetachedFromWindow();}
        @Override protected void onDraw(Canvas c){float cx=getWidth()/2f,cy=getHeight()/2f,s=Math.min(getWidth(),getHeight());p.setStyle(Paint.Style.FILL);p.setColor(mode==1||mode==2?accent:Color.TRANSPARENT);c.drawCircle(cx,cy,s*.45f,p);p.setColor(mode==1||mode==2?paper:ink);if(mix<1){p.setAlpha(Math.round(255*(1-mix)));glyph(c,oldMode,cx,cy,s);}p.setAlpha(Math.round(255*mix));glyph(c,mode,cx,cy,s);p.setAlpha(255);}
        private void glyph(Canvas c,int value,float cx,float cy,float s){if(value==8){p.setStyle(Paint.Style.STROKE);p.setColor(isActivated()?accent:ink);p.setStrokeWidth(s*.028f);p.setStrokeCap(Paint.Cap.ROUND);c.drawLine(cx-s*.15f,cy-s*.2f,cx+s*.15f,cy-s*.2f,p);c.drawLine(cx-s*.15f,cy+s*.2f,cx+s*.15f,cy+s*.2f,p);triangle.reset();triangle.moveTo(cx-s*.12f,cy-s*.18f);triangle.lineTo(cx+s*.12f,cy+s*.18f);triangle.lineTo(cx-s*.12f,cy+s*.18f);triangle.lineTo(cx+s*.12f,cy-s*.18f);triangle.close();c.drawPath(triangle,p);p.setStyle(Paint.Style.FILL);return;}if(value==9){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(s*.04f);triangle.reset();triangle.moveTo(cx-s*.24f,cy-s*.08f);triangle.lineTo(cx-s*.1f,cy-s*.08f);triangle.lineTo(cx+s*.04f,cy-s*.22f);triangle.lineTo(cx+s*.04f,cy+s*.22f);triangle.lineTo(cx-s*.1f,cy+s*.08f);triangle.lineTo(cx-s*.24f,cy+s*.08f);triangle.close();c.drawPath(triangle,p);c.drawArc(cx-s*.04f,cy-s*.22f,cx+s*.3f,cy+s*.22f,-58,116,false,p);p.setStyle(Paint.Style.FILL);return;}if(value>=4){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(s*.025f);p.setStrokeCap(Paint.Cap.ROUND);if(value==4){c.drawCircle(cx,cy,s*.2f,p);c.drawLine(cx,cy-s*.11f,cx,cy,p);c.drawLine(cx,cy,cx+s*.1f,cy+s*.045f,p);}else{if(value==5)p.setAlpha(Math.round(p.getAlpha()*.45f));c.drawArc(cx-s*.22f,cy-s*.18f,cx+s*.22f,cy+s*.18f,35,285,false,p);c.drawLine(cx+s*.18f,cy-s*.13f,cx+s*.23f,cy-s*.04f,p);c.drawLine(cx+s*.23f,cy-s*.04f,cx+s*.13f,cy-s*.045f,p);if(value>5){p.setStyle(Paint.Style.FILL);p.setTextSize(s*.18f);p.setTextAlign(Paint.Align.CENTER);c.drawText(value==6?"1":"★",cx,cy+s*.055f,p);}}p.setStyle(Paint.Style.FILL);return;}
            if(value==2){c.drawRoundRect(cx-s*.12f,cy-s*.14f,cx-s*.025f,cy+s*.14f,s*.012f,s*.012f,p);c.drawRoundRect(cx+s*.025f,cy-s*.14f,cx+s*.12f,cy+s*.14f,s*.012f,s*.012f,p);}else{float sign=value==0?-1:1;triangle.reset();triangle.moveTo(cx-sign*s*.12f,cy-s*.16f);triangle.lineTo(cx+sign*s*.16f,cy);triangle.lineTo(cx-sign*s*.12f,cy+s*.16f);triangle.close();c.drawPath(triangle,p);if(value==0||value==3)c.drawRoundRect(cx+sign*s*.18f-s*.022f,cy-s*.16f,cx+sign*s*.18f+s*.022f,cy+s*.16f,s*.01f,s*.01f,p);}}
    }
}
