const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
let checks=0;
const check=(condition,label)=>{checks++;assert.ok(condition,label);};
(async()=>{
  const directory=path.resolve(__dirname,'../record-android/assets/visual');
  const source=fs.readFileSync(path.join(directory,'audio-motion.js'),'utf8');
  const {features,AudioMotion}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
  const input={playing:true,signal:true,gain:1.4,rms:.1,bands:Array(16).fill(.2),wave:Array.from({length:32},(_,i)=>i%2?.2:-.2),lowVocal:.2,highVocal:.1,reduced:false};
  const old=features(input),max=features({...input,gain:4.2});
  check(Math.abs(max.energy/old.energy-3)<1e-6,'threefold energy sensitivity');
  check(Math.abs(max.bass/old.bass-3)<1e-6,'threefold low-frequency response');
  check(features({...input,signal:false}).energy===0,'missing signal gives no energy');
  check(features({...input,playing:false}).live===false,'paused playback has no live signal');
  check(features({...input,rms:100,gain:100}).energy===3,'bounded energy at maximum gain');
  check(features({...input,wave:Array(32).fill(0)}).live===false,'zero waveform cannot fabricate movement');
  const quiet={...input,rms:.005,bands:Array(16).fill(.005),lowVocal:.005,highVocal:.005};
  const low={...input,bands:Array.from({length:16},(_,i)=>i<6?.8:.005),lowVocal:.8,highVocal:.005};
  const high={...input,bands:Array.from({length:16},(_,i)=>i>9?.8:.005),lowVocal:.005,highVocal:.8};
  const motion=new AudioMotion();
  let result=motion.tick(quiet,.05);
  check(!result.beat&&result.phase>0,'first frame primes measured audio without a false attack');
  motion.tick(quiet,.05);motion.tick(quiet,.05);
  result=motion.tick(low,.05);
  check(result.beat&&result.boost>0&&result.onsetLeft>result.onsetRight,'low vocal transient selects left fighter');
  check(!motion.tick(low,.02).beat,'unchanged audio cannot repeat punches');
  for(let i=0;i<6;i++)motion.tick(quiet,.05);
  result=motion.tick(high,.05);
  check(result.beat&&result.onsetRight>result.onsetLeft,'high vocal transient selects right fighter');
  const phase=result.phase;
  result=motion.tick({...input,signal:false},.02);
  check(!result.beat&&result.phase===phase,'signal loss cannot advance movement or trigger hits');
  result=motion.tick({...input,playing:false},.02);
  check(result.phase===phase&&!result.live,'paused scene stays still');
  result=motion.tick({...input,reduced:true},.02);
  check(result.phase===phase,'reduced motion disables scene phase');
  check(!result.beat,'reduced motion does not fabricate a transient');
  const gainChange=new AudioMotion();gainChange.tick(input,.05);gainChange.tick(input,.05);
  check(!gainChange.tick({...input,gain:4.2},.05).beat,'changing sensitivity is not a music onset');
  const interval=(wait)=>{const m=new AudioMotion();m.tick(quiet,.05);m.tick(quiet,.05);let r;for(let n=0;n<4;n++){r=m.tick(low,.05);for(let i=0;i<wait;i++)m.tick(quiet,.05);}return {interval:r.interval,tempo:r.tempo};};
  const fast=interval(2),slow=interval(10);
  check(fast.interval>0&&fast.interval<slow.interval&&fast.tempo>slow.tempo,'observed faster onsets shorten attack cadence');
  const still=new AudioMotion();still.tick(input,.05);const held=still.phase;
  check(still.tick({...input,wave:Array(32).fill(0)},.05).phase===held,'zero waveform cannot advance phase');
  check(features({...input,bands:Array(16).fill(0)}).centroid===0,'empty spectrum has no invented timbre');
  const url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
  const threeURL=url(fs.readFileSync(path.join(directory,'three.module.min.js'),'utf8'));
  const motionURL=url(source);
  const loadModule=async file=>import(url(fs.readFileSync(path.join(directory,file),'utf8')
    .replace("'./three.module.min.js'",JSON.stringify(threeURL)).replace("'./audio-motion.js'",JSON.stringify(motionURL))));
  const T=await import(threeURL);
  const {fighterTargets,createFighting}=await loadModule('game-scenes.js');
  const combat={energy:1,bass:.5,mid:.3,high:.2,lowVocal:.5,highVocal:.1,balance:.6,waveBalance:.15,centroid:.2,roughness:.3,onsetLeft:1,onsetRight:0,interval:.15,boost:1,live:true,reduced:false};
  const left=fighterTargets(combat,1,0),right=fighterTargets(combat,0,1);
  check(left.leftAdvance>0&&left.leftArm.ext>0&&left.rightAdvance===0&&left.rightArm.ext===0,'left onset produces only a left attack target');
  check(right.rightAdvance>0&&right.rightArm.ext>0&&right.leftAdvance===0&&right.leftArm.ext===0,'right onset produces only a right attack target');
  const timbre=fighterTargets({...combat,centroid:.9,roughness:.9},1,0);
  check(timbre.leftArm.pitch>left.leftArm.pitch&&timbre.leftArm.yaw>left.leftArm.yaw,'spectral timbre changes attack height and hook angle');
  const stopped=fighterTargets({...combat,live:false},1,1);
  check(stopped.leftAdvance===0&&stopped.rightAdvance===0&&stopped.leftKick.hip===0&&stopped.rightArm.ext===0,'missing live audio suppresses all attack targets');
  const root=new T.Group();
  const ctx={root,wavePoint:()=>0,look(){},
    group(parent,x=0,y=0,z=0){const o=new T.Group();o.position.set(x,y,z);parent.add(o);return o;},
    neutral(parent,geometry,color,x=0,y=0,z=0){const o=new T.Mesh(geometry,new T.MeshStandardMaterial({color}));o.position.set(x,y,z);parent.add(o);return o;},
    gradient(parent,geometry,x=0,y=0,z=0){return this.neutral(parent,geometry,0xffffff,x,y,z);}};
  const advance=createFighting(ctx),actors=root.children.filter(o=>o.isGroup);
  advance(combat,.03,true);
  check(actors[0].position.x>-1.05&&actors[1].position.x>1.05,'real left rig advances and the opponent receives recoil');
  for(let i=0;i<100;i++)advance({...combat,live:false},.05,false);
  advance({...combat,bass:.2,lowVocal:.1,high:.5,highVocal:.5,onsetLeft:0,onsetRight:1},.03,true);
  check(actors[1].position.x<1.05,'real right rig follows a high-side onset');
  for(let i=0;i<150;i++)advance({...combat,onsetLeft:1,onsetRight:1},.05,true);
  check(Math.abs(actors[0].position.x+1.05)<1e-6&&Math.abs(actors[1].position.x-1.05)<1e-6,'held onset values do not schedule repeated attacks');
  for(let i=0;i<150;i++)advance({...combat,live:false},.05,false);
  const rest=[];root.traverse(o=>rest.push([o.position.toArray(),o.rotation.toArray().slice(0,3)]));
  for(let i=0;i<20;i++)advance({...combat,live:false},.05,false);
  let index=0,drift=0;root.traverse(o=>{const previous=rest[index++];for(let k=0;k<3;k++)drift=Math.max(drift,Math.abs(o.position.toArray()[k]-previous[0][k]),Math.abs(o.rotation.toArray()[k]-previous[1][k]));});
  check(drift<1e-6,'silent rigs settle into neutral without a time-based routine');
  const {SceneFilter}=await loadModule('filters.js');
  const filter=new SceneFilter(800,1280),scene=new T.Scene(),camera=new T.Camera();
  const oldTarget={name:'previous'},viewport=new T.Vector4(3,5,700,1100);
  let target=oldTarget,renders=0;
  const renderer={getRenderTarget:()=>target,getViewport:o=>o.copy(viewport),setRenderTarget:t=>{target=t;},setViewport:v=>viewport.copy(v),render(){renders++;}};
  filter.render(renderer,scene,camera);
  check(renders===1&&target===oldTarget,'original mode uses direct rendering');
  filter.setMode(1);filter.render(renderer,scene,camera);
  check(renders===3&&target===oldTarget&&viewport.equals(new T.Vector4(3,5,700,1100)),'filter pass restores the previous target and viewport');
  filter.setMode(2);
  check(filter.target.width===133&&filter.target.height===213&&filter.target.texture.magFilter===T.NearestFilter,'pixel mode renders to a true low-resolution nearest-filter target');
  filter.setMode(3);
  check(filter.material.uniforms.uDither.value===1,'combined mode applies Bayer dithering on the pixel target');
  const failing={...renderer,render(){throw new Error('GPU failure');}};
  assert.throws(()=>filter.render(failing,scene,camera),/GPU failure/);
  check(target===oldTarget&&viewport.equals(new T.Vector4(3,5,700,1100)),'GPU failure still restores renderer state');
  filter.dispose();filter.dispose();
  assert.throws(()=>filter.render(renderer,scene,camera),/disposed/);checks++;
  for(const file of ['scenes.js','audio-motion.js','game-scenes.js','stage-scenes.js','filters.js']){
    const syntax=spawnSync(process.execPath,['--input-type=module','--check'],{input:fs.readFileSync(path.join(directory,file),'utf8'),encoding:'utf8'});
    assert.equal(syntax.status,0,syntax.stderr);
    checks++;
  }
  console.log(checks+' 3D audio motion and module syntax checks passed');
})().catch(error=>{console.error(error.message);process.exitCode=1;});
