package local.tossfront.youtubeweb;

/** Fixed first-party DOM probe. Clicks only an enabled, visible official skip control. */
final class WebProbe {
    static final String STATE_JS="(function(autoSkip){try{\nconst visible=e=>!!e&&e.getClientRects().length>0&&getComputedStyle(e).display!=='none'&&getComputedStyle(e).visibility!=='hidden'&&getComputedStyle(e).opacity!=='0';\nconst enabled=e=>visible(e)&&!e.disabled&&e.getAttribute('aria-disabled')!=='true';\nconst first=selector=>Array.from(document.querySelectorAll(selector)).find(enabled)||null;\nconst skip=first('.ytp-ad-skip-button,.ytp-ad-skip-button-modern,.ytp-skip-ad-button,ytm-player-ads button[aria-label=\"Skip ad\"],button[aria-label=\"Skip ads\"],button[aria-label=\"광고 건너뛰기\"],button[aria-label=\"광고 건너뛰기 버튼\"]');\nconst ad=!!skip||!!first('.ad-showing,.ytp-ad-player-overlay,.ytp-ad-text,ytm-ad-state-overlay,ytm-player-ads .ad-interrupting');\nif(autoSkip&&ad&&skip&&Date.now()-(window.__frontRecordSkipAt||0)>1500){window.__frontRecordSkipAt=Date.now();skip.click();}\nconst next=first('.ytp-next-button,button[aria-label=\"Next video\"],button[aria-label=\"다음 동영상\"]');\nconst previous=first('.ytp-prev-button,button[aria-label=\"Previous video\"],button[aria-label=\"이전 동영상\"]');\nconst u=new URL(location.href),v=document.querySelector('video');const id=u.searchParams.get('v')||(u.pathname.match(/^\\/shorts\\/([\\w-]+)/)||[])[1]||'';\nif(!(u.pathname==='/watch'||u.pathname.startsWith('/shorts/'))||!v)return JSON.stringify({active:false});\nconst m=navigator.mediaSession&&navigator.mediaSession.metadata,t=document.querySelector('ytm-slim-video-metadata-renderer h1,ytm-watch-metadata h1,h1'),a=document.querySelector('ytm-slim-owner-renderer .slim-owner-channel-name,ytm-slim-owner-renderer a');\nwindow.__frontRecordAd=ad;\nif(!v.__frontRecordBound&&v.addEventListener){v.__frontRecordBound=true;v.addEventListener('ended',function(){const page=new URL(location.href),endedId=page.searchParams.get('v')||(page.pathname.match(/^\\/shorts\\/([\\w-]+)/)||[])[1]||'';window.__frontRecordEnded={id:endedId,at:Date.now(),ad:!!window.__frontRecordAd};});}\nconst end=window.__frontRecordEnded;\nreturn JSON.stringify({active:true,id:id,title:(m&&m.title)||(t&&t.textContent)||document.title.replace(/\\s*-\\s*YouTube$/,''),artist:(m&&m.artist)||(a&&a.textContent)||'YouTube 웹',duration:Number.isFinite(v.duration)?v.duration:0,position:Number.isFinite(v.currentTime)?v.currentTime:0,paused:v.paused,ended:v.ended,ready:v.readyState,speed:v.playbackRate,error:!!v.error,ad:ad,next:!!next,previous:!!previous,endedId:end&&!end.ad?end.id:'',endedAt:end&&!end.ad?end.at:0});\n}catch(e){return JSON.stringify({active:false});}})(AUTO_SKIP)";
    private static final String NAV_JS="(function(){const selectors=DIRECTION==='next'?'.ytp-next-button,button[aria-label=\"Next video\"],button[aria-label=\"다음 동영상\"]':'.ytp-prev-button,button[aria-label=\"Previous video\"],button[aria-label=\"이전 동영상\"]';for(const e of document.querySelectorAll(selectors)){if(e.getClientRects().length&&!e.disabled&&e.getAttribute('aria-disabled')!=='true'&&getComputedStyle(e).visibility!=='hidden'){e.click();return true;}}return false;})()";
    static final String SEEK_JS="(function(seconds){try{\nconst v=document.querySelector('video');if(!v||window.__frontRecordAd)return JSON.stringify({ok:false,reason:'unavailable'});\nlet target=Math.max(0,seconds),start=0,end=Number.isFinite(v.duration)?v.duration:Infinity;\nif(v.seekable&&v.seekable.length){start=v.seekable.start(0);end=v.seekable.end(v.seekable.length-1);}\nif(Number.isFinite(end))target=Math.max(start,Math.min(Math.max(start,end-.1),target));\nv.currentTime=target;v.dispatchEvent(new Event('timeupdate'));\nconst method='html';\nreturn JSON.stringify({ok:true,target:target,clamped:Math.abs(target-seconds)>.5,method:method});\n}catch(e){return JSON.stringify({ok:false,reason:'failed'});}})(SECONDS)";
    static String seek(long millis){return SEEK_JS.replace("SECONDS",Double.toString(Math.max(0,millis)/1000.0));}
    static String state(boolean skip){return STATE_JS.replace("AUTO_SKIP",Boolean.toString(skip));}
    static String navigate(boolean next){return NAV_JS.replace("DIRECTION",next?"'next'":"'previous'");}
    static String unmute(){return "(function(){const visible=e=>e&&e.getClientRects().length&&!e.disabled&&e.getAttribute('aria-disabled')!=='true'&&getComputedStyle(e).display!=='none'&&getComputedStyle(e).visibility!=='hidden'&&getComputedStyle(e).opacity!=='0';for(const e of document.querySelectorAll('.ytp-unmute,.ytp-unmute-button,button[aria-label*=\"음소거 해제\"],button[aria-label*=\"Unmute\"],button[aria-label*=\"unmute\"]')){if(visible(e)){e.click();return true;}}const v=document.querySelector('video');if(v){v.muted=false;if(v.volume===0)v.volume=1;}return false;})()";}
}
